### ISSUE TITLE
Duplicate of Active Game

### ISSUE THREAD

**Issue by josh-justjosh** [davwheat/world-cup-of-tocs-api#3]
![image](https://user-images.githubusercontent.com/54246291/105480465-b159b800-5c9d-11eb-864d-dc5cbdbb1a51.png)
It seems as though an instance of the active game (currently 7) is being displayed instead of game 8

**Comment by davwheat** [comment]
Fixed with fbcf4be7ff3f58834ce0c69c4555dd26eb69b82c and 7832633af23deefc2b9f02c7b0bec43a578b76e7.
