### ISSUE TITLE
Dates Unknown

### ISSUE THREAD

**Issue by josh-justjosh** [davwheat/world-cup-of-tocs-api#4]
davwheat/world-cup-of-tocs#12 seems to have caused all the dates on the site to be shown as **Date unknown**

**_Correction_**
Dates that are in the past (including today's) are showing unknown but future dates seem unaffected

**Comment by Gum-Joe** [comment]
Thank you! The issue now appears to have been fixed by 8c9ecb1cd763e418588f8310a12797e951f2fc24.

![image](https://user-images.githubusercontent.com/12299307/105519413-4aee8d00-5cd1-11eb-8cf4-ac7b78fbc54b.png)
